### PR TITLE
Remove docker-app plugin

### PR DESCRIPTION
**Pull request by StefanScherer**
docker app is not maintained, and can sometimes cause performance problems.
We want to remove it from Docker Desktop.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Do you know if we wanted to add a "stub" script that would print instructions (or a link) on how to install `docker app` (if we want to include this in 20.10.7 patch release), or only mention in the changelog / release notes?

**Comment by thaJeztah** [comment]
if we want to include this in 20.10.7, this needs to be cherry-picked into the 20.10 branch after merged to master

**Comment by StefanScherer** [comment]
I don't think we need it in 20.10.7 patch release, no hurry. We handle that removal in the Docker Desktop build pipeline right now.

**Review by thaJeztah — APPROVED** [review]
LGTM

should at least be fine for master 👍

**Pull request merged**
