### PR TITLE
deb, rpm: set minimum containerd version to 1.6.24

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to https://github.com/moby/moby/pull/46778

### CODE REVIEW

**Comment by thaJeztah** [comment]
@neersighted @cpuguy83 @corhere ptal

**Review by neersighted — APPROVED** [review]

**Review by corhere — COMMENTED** [review]
Is there a way to express that containerd 1.7 < v1.7.3 are incompatible?

**Comment by thaJeztah** [comment]
Maybe there is, but our package repos have never shipped packages for containerd 1.7, so if we would publish those, we would start with 1.7.8 or higher

**Review by corhere — APPROVED** [review]
Oh right, the major distros call their packages `containerd`, which would not satisfy a dependency on `containerd.io`

**Pull request merged**
