### PR TITLE
install recent Git version on CentOS 7

### PR DESCRIPTION
**Pull request by crazy-max**
follow-up https://github.com/docker/docker-ce-packaging/pull/631#issuecomment-1059363763

see also https://github.com/docker/docker-ce-packaging/pull/620#discussion_r793943247

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Wondering; would the trick with enabling GOPROXY work again for this one?

**Comment by thaJeztah** [comment]
Sight... and now CentOS 8 stream barfed out on this one `<flip>table</flip>` I'll kick it again

```
go mod tidy -modfile=vendor.mod
go: github.com/containerd/containerd@v1.5.5 requires
k8s.io/component-base@v0.20.6 requires
github.com/moby/term@v0.0.0-20200312100748-672ec06f55cd requires
gotest.tools@v2.2.0+incompatible: unrecognized import path "gotest.tools": https fetch: Get "https://gotest.tools/?go-get=1": read tcp 172.17.0.2:60960->216.239.34.21:443: read: connection reset by peer
```

**Comment by Romain-Geissler-1A** [comment]
Hi,

The latest build failed for a temporary network error, on raspbian, so is unrelated to this change. I guess it can be merged ?

Cheers,
Romain

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/docker-ce-packaging/pull/635 as alternative

**Pull request closed without merging**
