### PR TITLE
[master] update buildx to v0.10.0-rc1

### PR DESCRIPTION
**Pull request by thaJeztah**
release notes: https://github.com/docker/buildx/releases/tag/v0.10.0-rc1

### CODE REVIEW

**Comment by thaJeztah** [comment]
Ah, static builds failing, probably because of https://github.com/docker/buildx/pull/1268

```
mv: cannot stat './bin/buildx': No such file or directory
make[1]: *** [Makefile:107: static-buildx-plugin] Error 1
make[1]: Leaving directory '/home/ubuntu/workspace/docker-ce-packaging_PR-794/static'
make: *** [Makefile:97: static] Error 2
script returned exit code 2
```

/cc @crazy-max

**Comment by crazy-max** [comment]
Yes better to switch to:

```
DESTDIR=/usr/libexec/docker/cli-plugins VERSION=$(BUILDX_VERSION) REVISION=$(BUILDX_GITCOMMIT) make build
```

See https://github.com/docker/buildx/pull/1433

**Comment by crazy-max** [comment]
Btw I'm not sure we want to release an rc? Just for testing if packaging is still ok I guess?

**Comment by crazy-max** [comment]
I misunderstood, for static build change https://github.com/docker/docker-ce-packaging/blob/7054d8ef5e5f67d4a1525aafda22427ad836584f/static/Makefile#L107

to

```
cd $(BUILDX_DIR) && docker buildx bake --set binaries.platform=$(TARGETPLATFORM) binaries && mv ./bin/build/buildx ./bin/docker-buildx
```

**Comment by thaJeztah** [comment]
So this is master (and what's gonna be used for v23.0.0). Do you know when it will be "GA"? I thought if we're building a new v23.0.0 pre-release, we could deploy a new buildx (to the "test" channel) as well.

**Comment by thaJeztah** [comment]
> I misunderstood, for static build, change

Thanks! Applied that change, let's see if CI is happy 👍

**Comment by crazy-max** [comment]
> I thought if we're building a new v23.0.0 pre-release, we could deploy a new buildx (to the "test" channel) as well.

Ah yes I thought it was for 20.10 branch. It's fine then.

> Do you know when it will be "GA"?

We are doing multiple RCs this week and hopefully next week we have our GA for buildx/buildkit. cc @tonistiigi

**Comment by thaJeztah** [comment]
Cool; looks like CI is happy now; let me know if it LGTY, then we can merge

**Comment by thaJeztah** [comment]
Let's get this one in 👍

**Pull request merged**
