### PR TITLE
Bump Compose v2.32.0

### PR DESCRIPTION
**Pull request by ndeloof**
**- What I did**
Bump Compose v2.32.0

**- How I did it**

**- How to verify it**

**- Description for the changelog**

Compose v2.32.0

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by vvoland** [comment]
Uh, some issues with the armhf build on `ubuntu:noble`:
```
Reading package lists...

+ apt-get -y install --no-install-recommends apt-transport-https ca-certificates curl gnupg2 lsb-release software-properties-common

Reading package lists...

Building dependency tree...

Reading state information...

Some packages could not be installed. This may mean that you have

requested an impossible situation or if you are using the unstable

distribution that some required packages have not yet been created

or been moved out of Incoming.

The following information may help to resolve the situation:


The following packages have unmet dependencies:

 packagekit : Depends: libapt-pkg6.0t64 (>= 2.8.2) but 2.7.14build2 is to be installed

E: Unable to correct problems, you have held broken packages.

make: *** [Makefile:95: verify] Error 100

script returned exit code 2
```

**Comment by vvoland** [comment]
Not related to the compose bump, and other checks are green, so let me bring this one in.

**Comment by thaJeztah** [comment]
Kicked a rebuild to see if it picks up the fix that was merged in master (ISTR Jenkins will do a merge first, but not 100% sure)

if not, I'll do a quick rebase

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
