### PR TITLE
bump compose version to v2.24.0

### PR DESCRIPTION
**Pull request by jhrotko**

### CODE REVIEW

**Comment by glours** [comment]
@thaJeztah we closed the previous PR as it wasn't a fork branch and @jhrotko didn't have the right to push force to the branch the signed commit, can you please review this one?

**Review by glours — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Weird; something is failing in Jenkins; looks like it fails to checkout the branch for some reason 🤔 

```
+ make REF=bump-compose-2.24.0 raspbian-bookworm
git init src/github.com/docker/cli
Initialized empty Git repository in /home/ubuntu/workspace/docker-ce-packaging_PR-977/src/github.com/docker/cli/.git/
git -C src/github.com/docker/cli remote add origin "https://github.com/docker/cli.git"
./scripts/checkout.sh src/github.com/docker/cli "bump-compose-2.24.0"
+ SRC=src/github.com/docker/cli
+ REF=bump-compose-2.24.0
+ REF_FETCH=bump-compose-2.24.0
+ git -C src/github.com/docker/cli ls-remote --refs --heads --tags origin bump-compose-2.24.0
+ awk {print $2}
+ REF=
+ [ -n  ]
+ REF=FETCH_HEAD
+ git -C src/github.com/docker/cli fetch --update-head-ok --depth 1 origin bump-compose-2.24.0
fatal: couldn't find remote ref bump-compose-2.24.0
make: *** [Makefile:50: checkout-cli] Error 128
script returned exit code 2
```

**Comment by thaJeztah** [comment]
Wait... it's trying to checkout `bump-compose-2.24.0` in the CLI repository???? how the ... does that happen?

```
git -C src/github.com/docker/cli remote add origin "https://github.com/docker/cli.git"
./scripts/checkout.sh src/github.com/docker/cli "bump-compose-2.24.0"
```

**Comment by thaJeztah** [comment]
wondering if it’s some env-var (`REF`) that’s too generic and inherited somewhere 🤔

**Comment by thaJeztah** [comment]
Looking at older PR runs, `REF` would use the target branch (`master`);

Screenshot 2024-01-11 at 14 49 42

**Comment by thaJeztah** [comment]
Maybe it gets confused because the old "wrong" branch still exists in this repository; I'll try deleting that one (but looks like branch protections blocks removing it 😂 )


Screenshot 2024-01-11 at 15 34 39

**Comment by thaJeztah** [comment]
OH!!! the problem was in plain sight! But it revealed itself when I removed that stray branch; I see this PR was targeting that stray branch, not `master`

Screenshot 2024-01-11 at 15 47 31

I can do a quick PR to replace this one

**Comment by thaJeztah** [comment]
- opened https://github.com/docker/docker-ce-packaging/pull/978

Minor nit; @jhrotko it looks like you have your git configured without your "real name";

```
Signed-off-by: jhrotko <joana.hrotko@docker.com>
```

technically, DCO sign-off require to use your full name (see https://github.com/docker/cli/blob/master/CONTRIBUTING.md#sign-your-work);

```
Signed-off-by: YourFirsName YourLastName <yourname@example.org>
```

Steps to do so "roughly" come down to:


```bash
git config --global user.name "YourFirstName YourLastName"
git config --global user.email "yourname@example.org"
```


After that, signing off (`-s` /  `--signoff`) should use the details your configured above.

**Pull request closed without merging**
