### PR TITLE
Add systemd scripts

### PR DESCRIPTION
**Pull request by seemethere**
Adds systemd scripts from the [moby/moby](https://github.com/moby/moby) repo, preserving history of the scripts themselves.

Still left to do:

- [x] Edit scripts to actually be used by the *spec and deb files

### CODE REVIEW

**Comment by seemethere** [comment]
Should be ready for merge now @andrewhsu, @rogaha

**Comment by rogaha** [comment]
Thanks for the putting this together so fast @seemethere! I appreciate it!

**Comment by rogaha** [comment]
ping @andrewhsu

**Comment by andrewhsu** [comment]
LGTM

**Pull request merged**
