### PR TITLE
deb: use upstream init script

### PR DESCRIPTION
**Pull request by neersighted**
As per the title; prefer the upstream version of the init script.

This resolves https://github.com/docker/docker-ce-packaging/issues/899.

### CODE REVIEW

**Review by tianon — APPROVED** [review]

**Comment by neersighted** [comment]
```diff
--- docker-ce-packaging/deb/common/docker-ce.docker.init	2023-07-21 10:51:08
+++ moby/contrib/init/sysvinit-debian/docker	2023-07-18 13:15:44
@@ -44,14 +44,6 @@
 	exit 1
 fi
 
-check_init() {
-	# see also init_is_upstart in /lib/lsb/init-functions (which isn't available in Ubuntu 12.04, or we'd use it directly)
-	if [ -x /sbin/initctl ] && /sbin/initctl version 2>/dev/null | grep -q upstart; then
-		log_failure_msg "$DOCKER_DESC is managed via upstart, try using service $BASE $1"
-		exit 1
-	fi
-}
-
 fail_unless_root() {
 	if [ "$(id -u)" != '0' ]; then
 		log_failure_msg "$DOCKER_DESC must be run as root"
@@ -59,37 +51,10 @@
 	fi
 }
 
-cgroupfs_mount() {
-	# see also https://github.com/tianon/cgroupfs-mount/blob/master/cgroupfs-mount
-	if grep -v '^#' /etc/fstab | grep -q cgroup \
-		|| [ ! -e /proc/cgroups ] \
-		|| [ ! -d /sys/fs/cgroup ]; then
-		return
-	fi
-	if ! mountpoint -q /sys/fs/cgroup; then
-		mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup
-	fi
-	(
-		cd /sys/fs/cgroup
-		for sys in $(awk '!/^#/ { if ($4 == 1) print $1 }' /proc/cgroups); do
-			mkdir -p $sys
-			if ! mountpoint -q $sys; then
-				if ! mount -n -t cgroup -o $sys cgroup $sys; then
-					rmdir $sys || true
-				fi
-			fi
-		done
-	)
-}
-
 case "$1" in
 	start)
-		check_init
-		
 		fail_unless_root
 
-		cgroupfs_mount
-
 		touch "$DOCKER_LOGFILE"
 		chgrp docker "$DOCKER_LOGFILE"
 
@@ -110,14 +75,13 @@
 			--pidfile "$DOCKER_SSD_PIDFILE" \
 			--make-pidfile \
 			-- \
-				-p "$DOCKER_PIDFILE" \
-				$DOCKER_OPTS \
-					>> "$DOCKER_LOGFILE" 2>&1
+			-p "$DOCKER_PIDFILE" \
+			$DOCKER_OPTS \
+			>> "$DOCKER_LOGFILE" 2>&1
 		log_end_msg $?
 		;;
 
 	stop)
-		check_init
 		fail_unless_root
 		if [ -f "$DOCKER_SSD_PIDFILE" ]; then
 			log_begin_msg "Stopping $DOCKER_DESC: $BASE"
@@ -129,9 +93,8 @@
 		;;
 
 	restart)
-		check_init
 		fail_unless_root
-		docker_pid=`cat "$DOCKER_SSD_PIDFILE" 2>/dev/null`
+		docker_pid=$(cat "$DOCKER_SSD_PIDFILE" 2> /dev/null || true)
 		[ -n "$docker_pid" ] \
 			&& ps -p $docker_pid > /dev/null 2>&1 \
 			&& $0 stop
@@ -139,13 +102,11 @@
 		;;
 
 	force-reload)
-		check_init
 		fail_unless_root
 		$0 restart
 		;;
 
 	status)
-		check_init
 		status_of_proc -p "$DOCKER_SSD_PIDFILE" "$DOCKERD" "$DOCKER_DESC"
 		;;
 
```

**Review by thaJeztah — DISMISSED** [review]
LGTM if green 👍

**Comment by neersighted** [comment]
Went ahead and did it for the `default` file as well; diff is empty.

**Comment by thaJeztah** [comment]
was about to ask; one of the symlinks is to a directory, not a file, that's correct?

**Comment by neersighted** [comment]
This entire "deliberate dangling symlink" business is dangerous and https://github.com/docker/docker-ce-packaging/issues/925 is definitely a priority here, I'd say.

**Comment by thaJeztah** [comment]
For the 24.0 branch, the diff looks like this;

```patch
diff --git a/deb/common/docker-ce.docker.init b/Users/thajeztah/Projects/docker/contrib/init/sysvinit-debian/docker
index 9c8fa6be73..90dbe3c956 100755
--- a/deb/common/docker-ce.docker.init
+++ b/Users/thajeztah/Projects/docker/contrib/init/sysvinit-debian/docker
@@ -46,7 +46,7 @@ fi

 check_init() {
        # see also init_is_upstart in /lib/lsb/init-functions (which isn't available in Ubuntu 12.04, or we'd use it directly)
-       if [ -x /sbin/initctl ] && /sbin/initctl version 2>/dev/null | grep -q upstart; then
+       if [ -x /sbin/initctl ] && /sbin/initctl version 2> /dev/null | grep -q upstart; then
                log_failure_msg "$DOCKER_DESC is managed via upstart, try using service $BASE $1"
                exit 1
        fi
@@ -85,7 +85,7 @@ cgroupfs_mount() {
 case "$1" in
        start)
                check_init
-
+
                fail_unless_root

                cgroupfs_mount
@@ -110,9 +110,9 @@ case "$1" in
                        --pidfile "$DOCKER_SSD_PIDFILE" \
                        --make-pidfile \
                        -- \
-                               -p "$DOCKER_PIDFILE" \
-                               $DOCKER_OPTS \
-                                       >> "$DOCKER_LOGFILE" 2>&1
+                       -p "$DOCKER_PIDFILE" \
+                       $DOCKER_OPTS \
+                       >> "$DOCKER_LOGFILE" 2>&1
                log_end_msg $?
                ;;

@@ -131,7 +131,7 @@ case "$1" in
        restart)
                check_init
                fail_unless_root
-               docker_pid=`cat "$DOCKER_SSD_PIDFILE" 2>/dev/null`
+               docker_pid=$(cat "$DOCKER_SSD_PIDFILE" 2> /dev/null || true)
                [ -n "$docker_pid" ] \
                        && ps -p $docker_pid > /dev/null 2>&1 \
                        && $0 stop
```

**Review by tianon — APPROVED** [review]
(verified both paths via copy paste into my checkout of `docker/docker` and `ls -l` :+1:)

**Review by thaJeztah — APPROVED** [review]
re-LGTM (with the paths fixed 😅)

**Pull request merged**
