### PR TITLE
[20.10 backport] compose: bump version to v2.14.0

### PR DESCRIPTION
**Pull request by milas**
https://github.com/docker/compose/releases/tag/v2.14.0

(cherry picked from commit 66536b7633dc40f4557c23e6a3437a9f353e042e aka #789)

### CODE REVIEW

**Review by glours — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
```
 > [linux/amd64->darwin/arm64 build 1/1] RUN --mount=ro --mount=type=cache,target=/root/.cache     --mount=from=dockercore/golang-cross:xx-sdk-extras,target=/xx-sdk,src=/xx-sdk     --mount=type=tmpfs,target=cli/winresources     xx-go --wrap &&     TARGET=/out ./scripts/build/binary &&     xx-verify $([ "static" = "static" ] && echo "--static") /out/docker:
#24 0.616 Building static docker-darwin-arm64
#24 69.79 # github.com/docker/cli/vendor/github.com/miekg/pkcs11
#24 69.79 cgo: malformed DWARF TagVariable entry
```

Hmm. Looks like we're running into the same issue as with BuildKit; https://github.com/moby/moby/issues/44570

It's a bug / incompatibility in Go with newer versions of LLVM. I opened a backport in Go for Go 1.18, but that won't make it in until go1.18.10 (go1.18.9 will be a security release) In the meantime we should pin the alpine version to 3.16, similar to https://github.com/moby/buildkit/pull/3353

See

- https://github.com/moby/moby/issues/44570
- https://github.com/golang/go/issues/57044
- https://github.com/golang/go/pull/57067


Let me look at that.

**Comment by thaJeztah** [comment]
Opened;

- https://github.com/docker/cli/pull/3896
- https://github.com/docker/cli/pull/3897

**Comment by thaJeztah** [comment]
All green now, with the fixes / workaround merged in docker/cli 🎉

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
