### PR TITLE
Add Ubuntu 24.04 "Noble Numbat"

### PR DESCRIPTION
**Pull request by AkihiroSuda**
See https://wiki.ubuntu.com/Releases

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks! I had this one on my list to look at, but didn't look yet what the best moment would be for it to be "stable" enough to start building packages. Looking at https://discourse.ubuntu.com/t/noble-numbat-release-schedule/35649, I think they already froze features and froze pulling in debian, so I _guess_ it's stable "enough" to "soft release" packages.

Screenshot 2024-03-06 at 12 28 15



:warning: Jenkins currently passes, because it didn't pick up your changes yet, but it _will_ fail currently because it won't have containerd packages. We need to look when we can publish those packages, as that would be needed before we can include these.

cc @neersighted @vvoland

**Comment by AkihiroSuda** [comment]
- https://github.com/docker/containerd-packaging/pull/330

**Comment by p5** [comment]
These have been merged :tada: 
I think Ubuntu and Fedora PRs are now unblocked.

https://github.com/docker/containerd-packaging/pull/344

**Comment by lucianor** [comment]
Noble has been out for a while, but still no packages for it on the repository (or docs).. when we should expect that to happen?
I'm holding my homelab migration pending the package availability to prevent a dependency nightmare...

**Comment by thaJeztah** [comment]
containerd packages for 24.0.4 are now deployed; carrying this PR to make the Jenkinsfile changes be picked up;

- https://github.com/docker/docker-ce-packaging/pull/1006

**Pull request closed without merging**
