### PR TITLE
update buildx to v0.11.2

### PR DESCRIPTION
**Pull request by crazy-max**
release notes: https://github.com/docker/buildx/releases/tag/v0.11.2

### CODE REVIEW

**Review by neersighted — APPROVED** [review]

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
- relates to https://github.com/docker/docker-ce-packaging/pull/921

**Comment by crazy-max** [comment]
Known issue with `download.docker.com`? https://ci-next.docker.com/public/blue/organizations/jenkins/docker-ce-packaging/detail/PR-922/1/pipeline/1764#step-1765-log-382

```
Fetched 593 kB in 1s (691 kB/s)
E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/jammy/pool/test/armhf/containerd.io_1.6.21-1_armhf.deb  421  Unknown [IP: 13.32.151.52 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by neersighted** [comment]
Just worked fine for me -- AWS having issues?

**Comment by thaJeztah** [comment]
Interesting. Yeah, let's kick it again

**Comment by thaJeztah** [comment]
looks happy now 👍

**Pull request merged**
