### PR TITLE
[master] buildx: use v0.4.1

### PR DESCRIPTION
**Pull request by tonistiigi**
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tiborvass PTAL

**Comment by tonistiigi** [comment]
Looks like we have v0.4.1 incoming https://github.com/docker/buildx/issues/265

**Comment by thaJeztah** [comment]
Yes, saw that one 1 minute after I LGTM'd 😂

**Comment by tonistiigi** [comment]
Updated to v0.4.1

**Pull request merged**
