### PR TITLE
Add Fedora 32, remove Fedora 29

### PR DESCRIPTION
**Pull request by thaJeztah**
addresses https://github.com/docker/for-linux/issues/955

### CODE REVIEW

**Comment by ItsWendell** [comment]
Will this mean docker will show up at https://download.docker.com/linux/fedora/32/ soon?

**Comment by stefan8** [comment]
Still no builds for 32 :disappointed:

**Comment by dBitech** [comment]
From the Fedora Program management Group: Fedora 32 is GO and will ship on Tuesday 28 April!

**Comment by nysos3** [comment]
Over a week since the release of Fedora 32, and Docker is the only repo I have that's missing support. Any chance of a release soon? :smiling_face_with_three_hearts:

**Comment by verhoek** [comment]
Any update? It's been some time now and it's still missing

**Comment by ArturGajowy** [comment]
Still no packages for Fedora 32 available. Is there an ETA?

**Comment by samiconductor** [comment]
I took the hint and switched to `moby-engine` and it worked fine except moby on Fedora enables SELinux so I had to [add the z/Z flag to volumes](https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker/31334443#31334443). I found [this article](https://www.linuxuprising.com/2019/11/how-to-install-and-use-docker-on-fedora.html) helpful for getting docker alternatives setup on Fedora 31/32. Hope that helps!

**Comment by makkarpov** [comment]
Packages are still missing

**Pull request merged**
