### PR TITLE
Remove BindsTo

### PR DESCRIPTION
**Pull request by crosbymichael**
We want the docker container to run and not be restarted when containerd
is restarted.  Their lifecycles should not be coupled and docker can run
without the daemon.

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
Requires will not work as if containerd is explicitly stopped, docker will be stopped

**Comment by seemethere** [comment]
Which is what we want right? Since the daemon isn't really useful without containerd

**Comment by crosbymichael** [comment]
I don't think we should bump it as it will reconnect without having to go through a docker restart

**Comment by crosbymichael** [comment]
Closing this for now.

**Pull request closed without merging**
