### PR TITLE
deb: add docker-compose-plugin package

### PR DESCRIPTION
**Pull request by ndeloof**
Adds a deb package for the docker-compose cli plugin (rc3)

### CODE REVIEW

**Comment by thaJeztah** [comment]
This only checks out the source, correct? Wondering why this was opened, as there's https://github.com/docker/docker-ce-packaging/pull/553 as well

**Comment by ndeloof** [comment]
something went wrong with my git history it seems, my goal was to build on top of #553 to reflect move to github.com/docker/compose with 2.0.0-rc.3

**Comment by thaJeztah** [comment]
oh! I think I already did that, but looks like I haven't pushed yet 😂 let me do so

**Comment by thaJeztah** [comment]
Yup, LOL

```
Switched to branch 'add_compose_cli_package'
Your branch and 'origin/add_compose_cli_package' have diverged,
and have 3 and 3 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
```

**Comment by thaJeztah** [comment]
Pushed; https://github.com/docker/docker-ce-packaging/pull/553 should now be pointing at the new repository

**Pull request closed without merging**
