### PR TITLE
[19.03 backport] rpm: remove Fedora 31 as it's EOL

### PR DESCRIPTION
**Pull request by thaJeztah**
backport of https://github.com/docker/docker-ce-packaging/pull/523 for 19.03

### CODE REVIEW

**Comment by thaJeztah** [comment]
@silvin-lubecki @tiborvass PTAL

**Review by silvin-lubecki — APPROVED** [review]
LGTM

**Review by chris-crone — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
I'm merging this

**Pull request merged**
