### PR TITLE
Bump compose v2.26.0

### PR DESCRIPTION
**Pull request by dock-tor**
**- What I did**

Bump compose v2.26.0

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by glours — APPROVED** [review]

**Review by neersighted — APPROVED** [review]

**Review by krissetto — APPROVED** [review]

**Comment by thaJeztah** [comment]
@glours is `@dock-tor` a bot account? I see it uses @ndeloof's  name and e-mail for the commit / DCO sign off, which is slightly confusing 🤔 

Is it possible to to update the profile for that account to make it make it more "identifiable" ?

**Comment by ndeloof** [comment]
@thaJeztah my bad, this is GH account using my @docker.com email address, wrong browser used when creating this PR

**Comment by thaJeztah** [comment]
Oh! 😂 right.

Do you want to merge this one as-is, or prefer to have a PR opened with your account instead?

**Comment by ndeloof** [comment]
commit has my sign-off so I don't care about the PR

**Pull request merged**
