### PR TITLE
Require a containerd.io version >= 1.2.2

### PR DESCRIPTION
**Pull request by seemethere**
Hardcodes the requirement for containerd.io to be greater than or equal to 1.2.2

Signed-off-by: Eli Uriegas <eli.uriegas@docker.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
I'm -1 on this change if this only is to make containerd automatically update; I don't think we should _enforce_ a new version

**Comment by andrewhsu** [comment]
This is needed to get a bugfix in the runc.

**Comment by thaJeztah** [comment]
I'm really not comfortable with this change; I don't think we should _block_ older releases, but instead use `recommends >= 1.2.2`. This change prevents people from downgrading, and effectively we're back to square 1 where docker and containerd are in the same package

**Comment by andrewhsu** [comment]
Hmm..I dug a little more into the spec file `recommends` and I think we can explore some of the use cases more and consider a git revert if we need before the GA release. I still have opinions about the desirable workflow, but willing to be convinced differently.

**Pull request merged**
