### PR TITLE
[20.10 backport] update compose to v2.10.0

### PR DESCRIPTION
**Pull request by thaJeztah**
- backport of https://github.com/docker/docker-ce-packaging/pull/742

release notes: https://github.com/docker/compose/releases/tag/v2.10.0

(cherry picked from commit e5880f623468ce06e4f20dee772879eafbee5bbf)

### CODE REVIEW

**Comment by thaJeztah** [comment]
@milas @glours PTAL

**Review by glours — APPROVED** [review]
LGTM

**Review by milas — DISMISSED** [review]
👍

**Comment by thaJeztah** [comment]
Applied my "WIP" patch here as well to test https://github.com/docker/compose/pull/9771

**Comment by thaJeztah** [comment]
https://github.com/docker/docker-ce-packaging/pull/746 was merged, so this can be moved out of draft again; I'll merge this if CI goes green

**Review by crazy-max — APPROVED** [review]

**Pull request merged**
