### PR TITLE
[master] rpm: remove Fedora 31 as it's EOL

### PR DESCRIPTION
**Pull request by thaJeztah**
relates to https://github.com/docker/containerd-packaging/pull/211

### CODE REVIEW

**Comment by thaJeztah** [comment]
@silvin-lubecki @tiborvass PTAL

**Review by silvin-lubecki — APPROVED** [review]
LGTM

**Review by chris-crone — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
I'm merging this

**Pull request merged**
