### PR TITLE
Add Ubuntu 20.04 Focal Fossa

### PR DESCRIPTION
**Pull request by DeeDeeG**
Hi folks,

I am filing this pull request in an attempt to partly address https://github.com/docker/for-linux/issues/940 (for Ubuntu 20.04 Focal Fossa).

Not sure if this is the exact right way to do this, but thought I'd give it a shot.

Thanks.

P.S. I expect this would need to be added to a release branch, such as `19.03`, but I figure adding it to `master` is the proper first step.

### CODE REVIEW

**Comment by DeeDeeG** [comment]
I have built and used the "Focal Fossa" .deb package that one can produce, given the changes in my Pull Request.

It's working fine! No problems building, installing, or using it. I'd say this is ready to be on the nightly channel, at least? Not that I have a direct say, just wanted to report the good results!

**Comment by DeeDeeG** [comment]
Just a heads up: You may not want to merge this PR from me, as I have signed my commit with a pseudonym (my GitHub username). I'm totally fine if this gets re-implemented by someone else, I just want to bring Docker CE's readiness up for Focal, which comes out in just a bit over a month.

**Comment by darkdragon-001** [comment]
Would be nice to see this published **before** the actual release.

**Comment by DeeDeeG** [comment]
This is failing to build, but I remember seeing the same problem here: https://github.com/docker/containerd-packaging/pull/142#issuecomment-603128770

Solution (not found by me by the way) was to set an environment variable `DEBIAN_FRONTEND=noninteractive` before running `apt` or `apt-get`. (For exactly how this was fixed at the other repo, see: https://github.com/docker/containerd-packaging/pull/149)

Another lesson learned from that incident: It's good to use `--no-install-recommends`, since the `devscripts` package in Ubuntu 20.04 now has hundreds of (direct+indirect) dependencies.

I can implement these fixes here as well.

**Comment by DeeDeeG** [comment]
Okay, this branch is updated with the most basic fixes to build the `.deb` packages for `focal`, and it has also been rebased on top of the latest `master`.

---

I have even more (optional) changes, like `apt -get --no-install-recommends` and formatting tweaks in the `Dockerfile`, copied from https://github.com/docker/containerd-packaging/pull/149, in another branch: https://github.com/DeeDeeG/docker-ce-packaging/commits/ubuntu-20.04-fix. If you prefer all of those changes, I can push them to this branch.

---

cc'ing active people in this repo... @thaJeztah, @silvin-lubecki, @glours

**Comment by thaJeztah** [comment]
> I have even more (optional) changes, like apt -get --no-install-recommends and formatting tweaks in the Dockerfile, copied from docker/containerd-packaging#149, in another branch: https://github.com/DeeDeeG/docker-ce-packaging/commits/ubuntu-20.04-fix. If you prefer all of those changes, I can push them to this branch.

Thanks! I'm looking at some refactoring of this repository to make it more in line with the containerd packaging repository; I'd prefer to do that separate from this PR though.

**Comment by thaJeztah** [comment]
carried in https://github.com/docker/docker-ce-packaging/pull/451 🤗

**Comment by DeeDeeG** [comment]
Neat, thanks!

**Comment by darkdragon-001** [comment]
> E: The repository 'https://download.docker.com/linux/ubuntu focal Release' does not have a Release file.

How long will it take for the release to propagate to the respository?

**Comment by thaJeztah** [comment]
This will be included in the next (20.xx) Docker release

**Comment by deniseschannon** [comment]
@thaJeztah Is there a timeframe/roadmap for the next (20.xx) Docker release?

**Comment by claughinghouse** [comment]
@deniseschannon it looks like the release is now out. [Docker Ubuntu Dists](https://download.docker.com/linux/ubuntu/dists/)

**Comment by darkdragon-001** [comment]
So far, only `containerd.io` is present there: https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/

**Pull request closed without merging**
