### PR TITLE
[master] Makefile: use shallow clone

### PR DESCRIPTION
**Pull request by thaJeztah**
follow up to https://github.com/docker/docker-ce-packaging/pull/457

Before this change:

    make clean
    time make checkout
    git clone -q "https://github.com/docker/cli.git" src/github.com/docker/cli
    git clone -q "https://github.com/docker/docker.git" src/github.com/docker/docker
           69.16 real        15.69 user         9.69 sys

After this change:

    make clean
    time make checkout
    ...
    From https://github.com/docker/docker
     * branch            HEAD       -> FETCH_HEAD
    git -C src/github.com/docker/docker checkout -q FETCH_HEAD
           14.73 real         1.35 user         2.37 sys

### CODE REVIEW

**Comment by thaJeztah** [comment]
opened as a separate draft, because we had some issues with a similar change in the containerd packaging repository, so this might need some more work

**Comment by AkihiroSuda** [comment]
Does github support shallow-cloning non-HEAD commit?

**Comment by AkihiroSuda** [comment]
Ah, seems supported very recently: https://stackoverflow.com/questions/31278902/how-to-shallow-clone-a-specific-commit-with-depth-1#comment108853566_43136160

**Comment by thaJeztah** [comment]
Yes, correct, it wasn't supported in the past, but now is.

**Pull request merged**
