### PR TITLE
Add build target for ubuntu-eoan

### PR DESCRIPTION
**Pull request by arkodg**
Signed-off-by: Arko Dasgupta <arko.dasgupta@docker.com>

### CODE REVIEW

**Comment by arkodg** [comment]
PTAL @tiborvass @tonistiigi @andrewhsu @zelahi @thaJeztah

**Comment by thaJeztah** [comment]
@kolyshkin @seemethere ptal

**Comment by arkodg** [comment]
@seemethere thanks for the hint . I'm guessing this PR needs to get merged and another PR similar to https://github.com/docker/release-packaging/pull/318 needs to be raised in `release-packaging`

**Comment by seemethere** [comment]
I can’t see that PR but yes I’m assuming that’s the correct assumption.

**Pull request merged**
