### PR TITLE
[master] update to Compose v2.24.7

### PR DESCRIPTION
**Pull request by milas**
https://github.com/docker/compose/releases/tag/v2.24.7

### CODE REVIEW

**Comment by thaJeztah** [comment]
Arf, this needs a rebase now. We should probably look at adding some comments in between to reduce that probability (it's next to the `buildx` version)

I'll do a quick rebase.


also cc @dvdksn @vvoland for change-log (25.0.4)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
all green again; merging

**Comment by milas** [comment]
Thanks for the rebase & merge 😻

**Pull request merged**
