### PR TITLE
[master] bump compose version to v2.17.2

### PR DESCRIPTION
**Pull request by thaJeztah**
https://github.com/docker/compose/releases/tag/v2.17.2

### CODE REVIEW

**Review by glours — APPROVED** [review]

**Review by rumpl — APPROVED** [review]

**Comment by thaJeztah** [comment]
Hmm... panic during build?

```
docker buildx inspect | grep -q 'Driver: docker-container' || docker buildx create --use
boring_cohen
cd /home/ubuntu/workspace/docker-ce-packaging_PR-866/src/github.com/docker/cli && VERSION=0.0.0-20230326145633-59ec357 docker buildx bake --set binary.platform=darwin/amd64,darwin/arm64 binary
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x840767]

goroutine 1 [running]:
github.com/docker/buildx/bake/hclparser.(*parser).resolveValue(0xc0000a94a0, {0xc0002f4cf0, 0xa})
	/src/bake/hclparser/hclparser.go:244 +0xe27
github.com/docker/buildx/bake/hclparser.Parse({0x23087f8, 0xc00030e030}, {0x20ccb18?, 0xc000263710?, 0x20c95e0?}, {0x1e0ccc0?, 0xc000263740})
	/src/bake/hclparser/hclparser.go:358 +0xbcd
github.com/docker/buildx/bake.ParseFiles({0xc0003b02d0, 0x1, 0x19?}, 0x18?)
	/src/bake/bake.go:238 +0xa45
github.com/docker/buildx/bake.ReadTargets({0x13?, 0x0?}, {0xc0003b02d0?, 0xc00005e004?, 0x4b?}, {0xc000508ea0, 0x1, 0xc0005ff801?}, {0xc0001bb1e0, 0x1, ...}, ...)
	/src/bake/bake.go:88 +0x52
github.com/docker/buildx/commands.runBake({0x2318158, 0xc0003e02a0}, {0xc000508ea0, 0x1, 0x3}, {{0x329a860, 0x0, 0x0}, {0xc0001bb1e0, 0x1, ...}, ...})
	/src/commands/bake.go:106 +0xb2c
github.com/docker/buildx/commands.bakeCmd.func1(0xc0001c1680?, {0xc000508ea0, 0x1, 0x3})
	/src/commands/bake.go:182 +0x205
github.com/spf13/cobra.(*Command).execute(0xc0001c1680, {0xc0004905c0, 0x3, 0x3})
	/src/vendor/github.com/spf13/cobra/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000005b80)
	/src/vendor/github.com/spf13/cobra/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/src/vendor/github.com/spf13/cobra/command.go:918
github.com/docker/cli/cli-plugins/plugin.RunPlugin(0x1cacc60?, 0xc0001c1180, {{0x1fa6529, 0x5}, {0x1fb06f1, 0xb}, {0x22e4060, 0x7}, {0x0, 0x0}, ...})
	/src/vendor/github.com/docker/cli/cli-plugins/plugin/plugin.go:51 +0x130
main.runPlugin(0x1fe97e8?)
	/src/cmd/buildx/main.go:45 +0x105
main.main()
	/src/cmd/buildx/main.go:62 +0xf9
make[1]: *** [Makefile:74: cross-mac] Error 2
make[1]: Leaving directory '/home/ubuntu/workspace/docker-ce-packaging_PR-866/static'
make: *** [Makefile:97: static] Error 2
script returned exit code 2
```


/cc @crazy-max

**Comment by thaJeztah** [comment]
Oh! Looks like it's for the static builds only (not sure I checked that).


Wondering what version of buildx is running on these machines though;

```
  buildx: Docker Buildx (Docker Inc.)
    Version:  c5aec24
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
```


```
docker version
Client: Docker Engine - Community
 Version:           22.06.0-beta.0
 API version:       1.42
 Go version:        go1.18.3
 Git commit:        3e9117b
 Built:             Fri Jun  3 17:55:45 2022
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          22.06.0-beta.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.18.3
  Git commit:       38633e7
  Built:            Fri Jun  3 17:55:45 2022
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  c5aec24
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.12.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.17.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 22.06.0-beta.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-1022-aws
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.475GiB
 Name: ip-10-100-116-126
 ID: c944a62a-a99e-4e56-b148-df1906108e3b
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: dockerbuildbot
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

**Comment by thaJeztah** [comment]
discussed with @crazy-max 

- we'll temporarily revert the `null` values in the bake-file in docker/cli
- look at updating the CI machines to have a proper 23.0.x install (plus updated buildx)

**Comment by thaJeztah** [comment]
All green now 👍

**Pull request merged**
