### PR TITLE
[master] Add Ubuntu 24.04 "Noble Numbat" (carry 994)

### PR DESCRIPTION
**Pull request by thaJeztah**
- carries / closes https://github.com/docker/docker-ce-packaging/pull/994

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Hm.. interesting; noble is failing while trying to extract the tar;

```
docker run --rm -e PLATFORM -e EPOCH='5' -e DEB_VERSION=0.0.0~20240319100031.2356372 -e VERSION=0.0.0-20240319100031-2356372 -e CLI_GITCOMMIT=2356372 -e ENGINE_GITCOMMIT=23e1af4 -e BUILDX_VERSION=v0.13.1 -e BUILDX_DEB_VERSION=0.13.1 -e BUILDX_GITCOMMIT=7884339 -e COMPOSE_VERSION=v2.25.0 -e COMPOSE_DEB_VERSION=2.25.0 -v /home/ubuntu/workspace/docker-ce-packaging_PR-1006/deb/debbuild/ubuntu-noble:/build  debbuild-ubuntu-noble/aarch64
+ set -e
+ mkdir -p /root/build-deb/engine
+ tar -C /root/build-deb -xzf /sources/engine.tgz
tar: engine/daemon/config: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/stats: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/images: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/containerd: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/links: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/testdata: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/logger/loggerutils/cache: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/logger/loggerutils: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/logger/fluentd: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/logger/gelf: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/logger/etwlogs: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/logger/local: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/logger/templates: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/logger/gcplogs: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/logger/loggertest: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/logger/syslog: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/logger/splunk: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/logger/awslogs: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/logger/jsonfilelog/jsonlog: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/logger/jsonfilelog: Cannot change mode to rwxrwxr-x: Operation not permitted
tar: engine/daemon/logger/journald/internal/export/testdata: Cannot change mode to rwxrwxr-x: Operation not permitted
...
tar: Exiting with failure status due to previous errors
make[1]: *** [Makefile:80: ubuntu-noble] Error 2
make[1]: Leaving directory '/home/ubuntu/workspace/docker-ce-packaging_PR-1006/deb'
make: *** [Makefile:83: ubuntu-noble] Error 2
script returned exit code 2
```

**Comment by thaJeztah** [comment]
On `armhf` that is; looks like it's working as usual on the other architectures .. odd

**Comment by thaJeztah** [comment]
Disabling seccomp fixes this, but let me try if this works when using a ubuntu 22.04 host in Jenkins instead

**Comment by thaJeztah** [comment]
This needs work; the 20.04 agents had a variant for armhf which did a `setarch`. The 22.04 agents don't have a `armhf`  variant with that option set, and running on arm64 gives;


```
go 1.21
+ trap 'rm -f "${ROOTDIR}/go.mod"' EXIT
+ GO111MODULE=on
+ GOTOOLCHAIN=local
+ go build -mod=vendor -modfile=vendor.mod -o bundles/dynbinary-daemon/dockerd -tags ' journald' -buildmode=pie -ldflags '-w -X "github.com/docker/docker/dockerversion.Version=0.0.0-20240319100031-2356372" -X "github.com/docker/docker/dockerversion.GitCommit=4531a37" -X "github.com/docker/docker/dockerversion.BuildTime=2024-03-19T13:07:11.000000000+00:00" -X "github.com/docker/docker/dockerversion.PlatformName=Docker Engine - Community" -X "github.com/docker/docker/dockerversion.ProductName=docker" -X "github.com/docker/docker/dockerversion.DefaultProductLicense="   ' -gcflags= github.com/docker/docker/cmd/dockerd
# runtime/cgo
In file included from _cgo_export.c:4:
cgo-gcc-export-header-prolog:31:14: error: size of array ‘_check_for_64_bit_pointer_matching_GoInt’ is negative
+ rm -f /root/build-deb/engine/go.mod
make[1]: Leaving directory '/root/build-deb'
make[1]: *** [debian/rules:25: override_dh_auto_build] Error 1
make: *** [debian/rules:121: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
make[1]: *** [Makefile:80: raspbian-bullseye] Error 2
make[1]: Leaving directory '/home/ubuntu/workspace/docker-ce-packaging_PR-1006/deb'
make: *** [Makefile:83: raspbian-bullseye] Error 2
script returned exit code 2
```

**Comment by thaJeztah** [comment]
Oh, but only on raspbian

**Review by vvoland — APPROVED** [review]

**Review by neersighted — APPROVED** [review]

**Pull request merged**
