### PR TITLE
deb, rpm: inline go build for compose

### PR DESCRIPTION
**Pull request by thaJeztah**
- relates to https://github.com/docker/compose/pull/9744
- relates to https://github.com/docker/compose/pull/9771
- relates to https://github.com/docker/docker-ce-packaging/pull/742

The build.Makefile was removed from the compose repository, so copying the code to build the plugin here.

### CODE REVIEW

**Review by crazy-max — APPROVED** [review]

**Comment by thaJeztah** [comment]
@crazy-max I made a whoopsie (`$` instead of `$$`); think I have it fixed now, but let's see what CI says 😂

**Comment by thaJeztah** [comment]
crap. still wrong, guess I need `$(FOO)` after all

**Comment by thaJeztah** [comment]
sod it; I'll just inline it 😂

**Review by crazy-max — APPROVED** [review]

**Comment by thaJeztah** [comment]
Alright; let's get this one in 👍

**Pull request merged**
