### PR TITLE
[19.03 backport] bump Golang 1.13.10

### PR DESCRIPTION
**Pull request by thaJeztah**
backport of:

- https://github.com/docker/docker-ce-packaging/pull/455 [master] plugins/buildx: force go modules to use vendor mode 
- https://github.com/docker/docker-ce-packaging/pull/436 [master] Update Golang 1.13.8
- https://github.com/docker/docker-ce-packaging/pull/450 Update Golang 1.13.9
- https://github.com/docker/docker-ce-packaging/pull/453 Bump Golang 1.13.10

### CODE REVIEW

**Comment by thaJeztah** [comment]
Arf; CI is failing on Buildx; 

```
make[2]: Entering directory '/go/src/github.com/docker/app'
go build -tags="" -ldflags="-s -w -X github.com/docker/app/internal.GitCommit=7eea32b -X github.com/docker/app/internal.Version=v0.8.0 -X github.com/docker/app/internal.Experimental=off -X github.com/docker/app/internal.BuildTime=2020-04-14T12:25:48Z" -o bin/docker-app ./cmd/docker-app
make[2]: Leaving directory '/go/src/github.com/docker/app'
Cloning into '/go/src/github.com/docker/buildx'...
Fetching origin
+ go build -o bin/docker-buildx -ldflags '-X github.com/docker/buildx/version.Version=v0.3.1-tp-docker -X github.com/docker/buildx/version.Revision=6db68d029599c6710a32aa7adcba8e5a344795a7 -X github.com/docker/buildx/version.Package=github.com/docker/buildx -X main.experimental=1' ./cmd/buildx
go: github.com/containerd/containerd@v1.3.0-0.20190507210959-7c1e88399ec0: invalid pseudo-version: version before v1.3.0 would have negative patch number
debian/rules:12: recipe for target 'override_dh_auto_build' failed
make[1]: Leaving directory '/root/build-deb'
make[1]: *** [override_dh_auto_build] Error 1
debian/rules:67: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
Makefile:71: recipe for target 'ubuntu-xenial' failed
```

**Comment by thaJeztah** [comment]
Buildx is fixed on master through https://github.com/docker/buildx/pull/233, but that's not in the tag that we're using in the 19.03 branch

**Comment by thaJeztah** [comment]
Diff between v0.3.1 and master: https://github.com/docker/buildx/compare/v0.3.1...master
and diff between v0.3.1 and the commit that fixed Go 1.13 compatibility: https://github.com/docker/buildx/compare/v0.3.1...52b0ea328fee203354fb6fadf3bf5ac8fc22060f


Wondering if `52b0ea328fee203354fb6fadf3bf5ac8fc22060f` should be tagged as v0.3.2 (e.g.); assuming we don't want the update to builkit v0.7 in the version that we ship with 19.03

**Comment by thaJeztah** [comment]
@tiborvass @tonistiigi ^^ any ideas what's best?

**Comment by tonistiigi** [comment]
We can tag. Or that commit should be built with go1.12. The only tested configuration is the build process in the Dockerfile.

**Comment by thaJeztah** [comment]
Building with a different Go version would be a bit tricky as all binaries are built in the same environment (and hence would be built with the same go version). Given that `buildx` is shipped as an experimental feature/plugin, I think updating to a newer version would be ok (assuming current master plays "nice" with 19.03)

**Comment by thaJeztah** [comment]
I included https://github.com/docker/docker-ce-packaging/pull/455 to force Go modules to use vendor mode; and it's green now 🎉  (thanks @chris-crone for the suggestion!)

**Pull request merged**
