### PR TITLE
update Compose to v2.26.1

### PR DESCRIPTION
**Pull request by milas**
Update Compose to [v2.26.1](https://github.com/docker/compose/releases/tag/v2.26.1)

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
cc @vvoland

**Review by vvoland — APPROVED** [review]

**Comment by thaJeztah** [comment]
Hmm; armhf builds acting up again?

```

#14 5.623 Reading state information...
#14 5.857 Some packages could not be installed. This may mean that you have
#14 5.857 requested an impossible situation or if you are using the unstable
#14 5.857 distribution that some required packages have not yet been created
#14 5.857 or been moved out of Incoming.
#14 5.858 The following information may help to resolve the situation:
#14 5.858 
#14 5.858 The following packages have unmet dependencies:
#14 6.134  libelf1t64 : Breaks: libelf1 (< 0.190-1.1build2) but 0.190-1 is to be installed
#14 6.140 E: Unable to correct problems, you have held broken packages.
#14 ERROR: process "/bin/sh -c apt-get update && apt-get install -y curl devscripts equivs git" did not complete successfully: exit code: 100

**Comment by thaJeztah** [comment]
Oh, ubuntu 24.04; wondering if their package repo is being updated perhaps

**Comment by neersighted** [comment]
Looks like the noble repos are currently broken due to a rebuild triggered by Friday's xz revelations (https://discourse.ubuntu.com/t/whats-happening-in-noble-repositories/43729/7); they are simply unusable right now due to inconsistency and a mass rebuild.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
