### PR TITLE
[master] update Compose to v2.3.4

### PR DESCRIPTION
**Pull request by glours**
Signed-off-by: Guillaume Lours <guillaume.lours@docker.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Hmmm.. does kubernetes now require JSON or something? Or are they no longer compatible with go1.16?

```
GOOS=linux GOARCH=arm CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -X github.com/docker/compose/v2/internal.Version=v2.3.4"  -o /usr/libexec/docker/cli-plugins/docker-compose ./cmd
# sigs.k8s.io/json/internal/golang/encoding/json
/go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
/go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)

```

**Comment by thaJeztah** [comment]
CGO, not JSON (lol.. in two chats at the same time) 😂

**Comment by thaJeztah** [comment]
Guessing this could be related; looks like they copy Golang's code into their own repository; https://github.com/kubernetes-sigs/json/commit/80fe866be0a7e280be3a8b2a966745cce42adb18

**Comment by thaJeztah** [comment]
So that depends on Go 1.17 indeed, which introduced the `IsExported()` function; https://github.com/golang/go/commit/b83d073e9eb4cbd0cd5ca530f576668c49f6d0f1

**Comment by crazy-max** [comment]
As discussed with @thaJeztah you should have this replaces in compose: https://github.com/docker/buildx/blob/1ca30a58c2f25a7f72a2fdb5d62e82bf1e2fa37c/go.mod#L62-L64. See also https://github.com/docker/buildx/pull/948

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/compose/pull/9317 to pin the dependencies (but will need a new release after that)

**Comment by thaJeztah** [comment]
We updated master to go1.17, and I kicked CI for this PR

If we want to ship an updated version of compose before docker 22.xx is released, we need to have https://github.com/docker/compose/pull/9317 merged and a new version of compose

(this PR on master we can merge if CI goes green)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
