### PR TITLE
[master] [TAR-610] [TAR-611] Build the daemon as part of the package building process

### PR DESCRIPTION
**Pull request by seemethere**
Basically a reverse of #223.

Should hopefully resolve issues:
* https://github.com/moby/moby/issues/38175
* https://github.com/docker/for-linux/issues/452

Tested with `docker engine activate` and `docker engine update`, which work as expected.

cc @andrewhsu @thaJeztah

### CODE REVIEW

**Comment by instantlinux** [comment]
As noted in https://github.com/docker/for-linux/issues/452, version 19.05-ce still has the issue (missing support for devicemapper).

**Comment by seemethere** [comment]
@instantlinux There is no official `19.05-ce`

**Comment by instantlinux** [comment]
Sorry, misread the version string: 18.09.5 is the version I found which is still problematic. The docker-ce edge releases have gotten shockingly WAY behind the current calendar date (8 months and counting).

**Comment by thaJeztah** [comment]
@instantlinux edge releases are no more; see https://blog.docker.com/2018/07/extending-support-cycle-docker-community-edition/

**Comment by instantlinux** [comment]
Got it, OK...Docker should overhaul its top-level website, there's a whole lot of information there rendered obsolete by that one blog entry.

**Comment by thaJeztah** [comment]
Do you mean the docs.docker.com website, or www.docker.com? (could you point to an example page that's problematic? then I can try forwarding that to the right team)

**Comment by instantlinux** [comment]
It's the docs.docker.com site that needs attention. If you go to the main https://docs.docker.com/install/ section _About Docker CE_, the text reads about the same as it has for the past 3+ years and doesn't give a hint that "hey this stuff changed in the summer of 2018!" What I'd do is basically delete the whole discussion of the release versioning and nightly builds and phrase it entirely differently to present the material from a new-user's perspective along with a link to a page for the longtime-user audience. You could try tweaking it around the edges by (1) linking to one or more of the blog entries that you cited here to highlight past changes to the process, (2) providing far-better charts showing the available supported versions (with explicit references to the version strings that each distro accepts, e.g. "apt install docker-ce=18.09.bla-blah), and (3) making it clear that the calendar-date thing isn't really working anymore and that the company is now doing semver instead.

**Pull request merged**
